### ISSUE TITLE
Won't you be banned

### ISSUE THREAD

**Issue by kalerZ** [LucasLau00/buff163-Price-Monitor#2]
Won't you be banned by buff163

**Comment by LucasLau00** [comment]
I Suggest that you set the delay interval between requests to be higher and also add on HTTP/HTTPS proxy for requests.
It will generally deny you from accessing the api in the current request but will be fine later on. I personally had it running on a cloud server so Im unsure does it do any damage to your local IP. Your account will not be used to make those requests as they are GET requests and none of your account details are posted to the api.

**Comment by kalerZ** [comment]
Ask for advice how much between requests is appropriate？
